### PR TITLE
Revert change to route model binding

### PR DESCRIPTION
**Pull request by Riari**
As @deleugpn said [here](https://github.com/bitporch/laravel-forum/pull/88#discussion_r122663057), this isn't strictly necessary but I think there's too much magic happening without it, so I suggest keeping it.

### CODE REVIEW

**Comment by deleugpn** [comment]
- Riari wants to explicitly set it in the Service Provider;
- Dylan wants to move the binding for Group into the Model;

Which one should we do? Notice that either one is absolutely fine and this is just a matter of preference.

------------------------------------

As per my opinion, we're developing a package for Laravel and not meant to be used outside of it. Implicit Route Binding is something quite simple that often people don't know about or don't use. For that reason, I think using the standard implicit one shows how much easy that can be achieved by just relying on "Laravel Magic".
I would go with removing it all and setting the slug in the `Group` model for the group case.

**Comment by Riari** [comment]
When the issue was brought up on Larachat, I thought the suggestion was to change the Group model's primaryKey property to use the slug, plus I forgot/didn't realise `getRouteKey` is an actual Eloquent method and not just a suggestion for a custom helper method.

So on that basis, yeah, I'm in favour of using `getRouteKey` and just having the implicit `Route::model()` lines in the service provider. It's a good compromise between explicitness and "wtf is going on, I didn't tell it to do that" 😛

**Comment by deleugpn** [comment]
I like the compromise and I would add one last detail: 

- Move it to it's own method (`registerRouteBindings()`);
- Add a comment stating that Laravel do not require us to do it, but we want to explicitly let users of the package know that we're using Route Bindings

**Comment by Riari** [comment]
Cool. I'll update this later with those amendments 👍

**Comment by deleugpn** [comment]
I approve this changes, too!

**Pull request merged**
